CC=g++
CFLAGS=-W -Wall -ansi -pedantic -I ../common/inc/ -I ./inc/
LDFLAGS=
EXEC=release/t1

all: $(EXEC)

release/t1: obj/appli.o obj/t1.o
	$(CC) -o $@ $^ $(LDFLAGS)  ##$@ est le target , release/t1 dans ce cas

obj/appli.o: ../common/src/appli.cpp
	$(CC) -o $@ -c $< -W -Wall -ansi -pedantic -I ../common/inc/ -I ./inc/ 

obj/t1.o: src/t1.cpp ../common/inc/appli.h
	$(CC) -o $@ -c $< -W -Wall -ansi -pedantic -I ../common/inc/ -I ./inc/

clean:
	rm -rf obj/*.o

mrproper: clean
	rm -rf $(EXEC)

##http://gl.developpez.com/tutoriel/outil/makefile/

##output dir    http://stackoverflow.com/questions/1814270/gcc-g-option-to-place-all-object-files-into-separate-directory
##http://gl.developpez.com/tutoriel/outil/makefile/
##http://stackoverflow.com/questions/1139271/makefiles-with-source-files-in-different-directories
##test
